### ISSUE TITLE
Uncaught TypeError: Arguments to CompositeDisposable.add must have a .dispose() method

### ISSUE THREAD

**Issue by eskhool** [aki77/atom-source-preview#13]
Showing up in Atom 1.11.1 with source-preview 0.5.0
`TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:43:11)
    at new CompositeDisposable (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:19:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:265:29
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:388:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:366:19
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:97:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.didAddPane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:306:27)
    at Pane.module.exports.Pane.setContainer (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:131:26)
    at PaneAxis.module.exports.PaneAxis.addChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:144:13)
    at PaneAxis.module.exports.PaneAxis.insertChildAfter (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:216:19)
    at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:923:23)
    at Pane.module.exports.Pane.splitRight (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:884:19)
    at PreviewView.module.exports.PreviewView.show (/Users/anshu/.atom/packages/source-preview/lib/preview-view.coffee:111:23)
    at Object.module.exports.toggle (/Users/anshu/.atom/packages/source-preview/lib/main.coffee:33:13)
    at atom-text-editor.subscriptions.add.atom.commands.add.source-preview:toggle (/Users/anshu/.atom/packages/source-preview/lib/main.coffee:13:47)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
`

**Comment by resisttheurge** [comment]
Same issue.

[Enter steps to reproduce below:]
1. Create a Node project with the following package.json:

```
{
  "name": "js-lesson-build-tools",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build:watch": "webpack --watch",
    "build": "webpack",
    "start": "node ./dist/main.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.17.0",
    "babel-eslint": "^7.0.0",
    "babel-loader": "^6.2.5",
    "babel-polyfill": "^6.16.0",
    "babel-preset-latest": "^6.16.0",
    "babel-preset-stage-0": "^6.16.0",
    "standard": "^8.4.0",
    "webpack": "^1.13.2"
  },
  "babel": {
    "presets": ["latest", "stage-0"]
  },
  "standard": {
    "parser": "babel-eslint"
  }
}
```
1. Create a `.js` file with arbitrary es6 code (language support provided by the `language-babel` package
2. Use the command palette to trigger `Source Preview: Toggle` command
3. Receive error 🎉  

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [source-preview](https://github.com/aki77/atom-source-preview) package, v0.5.0

### Stack Trace

Uncaught TypeError: Arguments to CompositeDisposable.add must have a .dispose() method

```
At C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:70

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:70:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:43:11)
    at new CompositeDisposable (C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:19:14)
    at C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\src\workspace.js:265:29
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\src\pane-container.js:388:27)
    at C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\src\pane-container.js:366:19
    at C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\src\pane-container.js:97:16
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.didAddPane (C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\src\pane-container.js:306:27)
    at Pane.module.exports.Pane.setContainer (C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\src\pane.js:131:26)
    at PaneAxis.module.exports.PaneAxis.addChild (C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\src\pane-axis.js:144:13)
    at PaneAxis.module.exports.PaneAxis.insertChildAfter (C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\src\pane-axis.js:216:19)
    at Pane.module.exports.Pane.split (C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\src\pane.js:923:23)
    at Pane.module.exports.Pane.splitRight (C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\src\pane.js:884:19)
    at PreviewView.module.exports.PreviewView.show (file:///C:/Users/peter/.atom/packages/source-preview/lib/preview-view.coffee:111:23)
    at Object.module.exports.toggle (file:///C:/Users/peter/.atom/packages/source-preview/lib/main.coffee:33:13)
    at atom-text-editor.subscriptions.add.atom.commands.add.source-preview:toggle (file:///C:/Users/peter/.atom/packages/source-preview/lib/main.coffee:13:47)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\src\command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\src\window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (C:\Users\peter\AppData\Local\atom\app-1.11.1\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -0:47.4.0 core:undo (atom-text-editor.editor.is-focused)
     -0:45.3.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:45 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:44.4.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:43.8.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:43.8.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:43.8.0 editor:indent (atom-text-editor.editor.is-focused)
 15x -0:43 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
  2x -0:40.5.0 core:backspace (atom-text-editor.editor.is-focused)
 11x -0:34.1.0 blur (atom-text-editor.editor.is-focused)
     -0:04.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:02.9.0 blur (atom-text-editor.editor.is-focused)
     -0:01.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.8.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:01.8.0 source-preview:toggle (atom-text-editor.editor)
```

### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter-js-standard-engine",
      "source-preview-babel"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "atom-material-ui",
      "atom-material-syntax-light"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
adventurous-syntax, v0.2.0 (inactive)
aesthetic-ui, v2.0.0 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-light, v0.4.5 (active)
atom-material-ui, v1.3.6 (active)
batman-syntax, v1.0.1 (inactive)
docker, v0.7.0 (inactive)
elm-format, v2.1.0 (active)
emmet, v2.4.3 (active)
file-icons, v1.7.22 (active)
firewatch-syntax, v1.0.1 (inactive)
flat-light-syntax, v0.7.0 (inactive)
fonts, v1.6.0 (active)
git-hide, v0.1.2 (active)
git-time-machine, v1.5.3 (inactive)
github-atom-light-syntax, v0.2.0 (inactive)
gitignore-snippets, v0.2.5 (inactive)
goto, v1.7.1 (inactive)
gruvbox-plus-syntax, v1.2.5 (inactive)
language-babel, v2.44.1 (active)
language-batch, v0.3.3 (active)
language-docker, v1.1.7 (active)
language-elm, v1.5.0 (active)
language-gitignore, v0.3.0 (active)
linter, v1.11.18 (active)
linter-docker, v0.1.2 (active)
linter-elm-make, v0.17.7 (active)
linter-js-standard, v3.4.1 (active)
linter-js-standard-engine, v0.0.6 (inactive)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.0 (active)
minimap-bookmarks, v0.4.2 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-linter, v1.6.0 (active)
minimap-pigments, v0.2.1 (active)
minimap-selection, v4.4.0 (active)
monokai-soda, v0.5.0 (inactive)
pigments, v0.37.0 (active)
redmond-syntax, v1.0.2 (inactive)
script, v3.10.1 (inactive)
source-preview, v0.5.0 (active)
source-preview-babel, v0.2.1 (inactive)
standardjs-snippets, v2.4.0 (active)
tomorrow-night-eighties-syntax, v0.17.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by danielbayley** [comment]
I just ran into this too 😞

**Comment by d4nshields** [comment]
Varying the atom release but leaving the packages installed the same, I found that:

> Atom 1.10.2 WORKS (behaviour mentioned **is not** reproduced)
> Atom 1.11.0 FAILS (behaviour mentioned **is** reproduced)
> Atom 1.11.1 FAILS
> Atom 1.12.0-beta2 WORKS

Fortunately for me I am willing to switch to the Atom-beta channel temporarily as a workaround.   Perhaps whatever fix is applied will make its way eventually to the stable channel?    I don't know the specifics of whatever side-effect was introduced in Atom.  I suggest keeping this bug open until it is resolved in stable.
